codigo1 = int(input())
quantidade1 = int(input())
preco1 = float(input())
codigo2 = int(input())
quantidade2 = int(input())
preco2 = float(input())
total = (quantidade1 * preco1) + (quantidade2 * preco2)
print(f"VALOR A PAGAR: R$ {total:.2f}\n")